# .github/workflows/notify-website-dev.yml
name: Notify website (dev)

concurrency:
  group: tpblogs-dispatch
  cancel-in-progress: true 
  
on:
  push:
    branches: [ main ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to website/dev
        env:
          GH_TOKEN: ${{ secrets.WEBSITE_TOKEN }} # PAT with Actions: RW on website repo
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/talentpool-ai/TPWebsiteNextJs/dispatches \
            -d '{"event_type":"tpblogs-updated-dev","client_payload":{"ref":"dev"}}'
